### ISSUE TITLE
Bokeh data?

### ISSUE THREAD

**Issue by bryevdv** [scopatz/nf-project-inequality#6]
@scopatz How did you derive 

> "Bokeh": {"female": 1.0, "male": 6.0},

For Bokeh? If you just look either the NF committee, or the members of [`bokeh/core`](https://github.com/bokeh/bokeh/wiki/BEP-4:-Project-Roles#core-team), it would be:

 > "Bokeh": {"female": 1.0, "male": 4.0},

in either case. And it you pull the top 30 by "number of PRs", then it is:

> "Bokeh": {"female": 6.0, "male": 24.0},

Also what's up with the floating point :)

**Comment by scopatz** [comment]
I think this was from 6+ months ago, so the numbers are probably out of date.  PRs definitely welcome!

**Comment by scopatz** [comment]
Also, the floats are so the arrays don't get cast to ints for the underlying calcs
